In [15]:
using DataStructures
rawdata = readlines("input.txt")
p = r"(.*) would ([gl]).* (\d*) happiness units by sitting next to (.*)\."
sign = Dict("l"=>-1,"g"=>1)
func(x)=[x[1],x[4],sign[x[2]]*parse(Int,x[3])]
data = permutedims(reduce(hcat, map(func, match(p, line) for line in rawdata)))
data


56×3 Matrix{Any}:
 "Alice"    "Bob"       -57
 "Alice"    "Carol"     -62
 "Alice"    "David"     -75
 "Alice"    "Eric"       71
 "Alice"    "Frank"     -22
 "Alice"    "George"    -23
 "Alice"    "Mallory"   -76
 "Bob"      "Alice"     -14
 "Bob"      "Carol"      48
 "Bob"      "David"      89
 "Bob"      "Eric"       86
 "Bob"      "Frank"      -2
 "Bob"      "George"     27
 ⋮                     
 "George"   "Carol"     -60
 "George"   "David"      30
 "George"   "Eric"     -100
 "George"   "Frank"     -63
 "George"   "Mallory"    57
 "Mallory"  "Alice"     -71
 "Mallory"  "Bob"       -28
 "Mallory"  "Carol"     -10
 "Mallory"  "David"      44
 "Mallory"  "Eric"       22
 "Mallory"  "Frank"      79
 "Mallory"  "George"    -16

In [16]:
names = unique(data[:, :2])
indexes = Dict(names .=> 1:length(names))

Dict{SubString{String}, Int64} with 8 entries:
  "Carol"   => 2
  "Eric"    => 4
  "David"   => 3
  "George"  => 6
  "Alice"   => 8
  "Frank"   => 5
  "Bob"     => 1
  "Mallory" => 7

In [17]:
indexes = Dict(names .=> 1:length(names))
units = fill(0, (length(names),length(names)))
for line in 1:size(data,1)
    units[indexes[data[line, 1]], indexes[data[line,2]]] = data[line, 3]
end
units

8×8 Matrix{Int64}:
   0   48   89    86   -2   27   19  -14
  45    0   24     5  -68  -25   30   37
  34   99    0    91  -38   60  -63  -51
 -69  -33  -47     0   75   82   13   23
  27  -87   74   -41    0  -99   26   77
 -51  -60   30  -100  -63    0   57  -63
 -28  -10   44    22   79  -16    0  -71
 -57  -62  -75    71  -22  -23  -76    0

In [18]:
units = units + units'

8×8 Matrix{Int64}:
   0    93   123   17    25   -24    -9   -71
  93     0   123  -28  -155   -85    20   -25
 123   123     0   44    36    90   -19  -126
  17   -28    44    0    34   -18    35    94
  25  -155    36   34     0  -162   105    55
 -24   -85    90  -18  -162     0    41   -86
  -9    20   -19   35   105    41     0  -147
 -71   -25  -126   94    55   -86  -147     0

In [27]:
function max_happiness(loc, left, info)
    path = []
    max = -Inf
    if length(left) == 1
        if left[1] == 1
            return -Inf
        end
        return info[loc, left[1]] + info[left[1], 1]
    end
    for i in 1:length(left)
        _max = max_happiness(left[i], cat(left[1:i-1],left[i+1:end], dims=1), info)
        _max += info[loc, left[i]]
        if _max > max
            max = _max
        end
    end
    return max
end
max_happiness(1, 2:length(names), units)

618

In [24]:
newunits = vcat(hcat(units, zeros(length(names))),zeros(length(names)+1)')

9×9 Matrix{Float64}:
   0.0    93.0   123.0   17.0    25.0   -24.0    -9.0   -71.0  0.0
  93.0     0.0   123.0  -28.0  -155.0   -85.0    20.0   -25.0  0.0
 123.0   123.0     0.0   44.0    36.0    90.0   -19.0  -126.0  0.0
  17.0   -28.0    44.0    0.0    34.0   -18.0    35.0    94.0  0.0
  25.0  -155.0    36.0   34.0     0.0  -162.0   105.0    55.0  0.0
 -24.0   -85.0    90.0  -18.0  -162.0     0.0    41.0   -86.0  0.0
  -9.0    20.0   -19.0   35.0   105.0    41.0     0.0  -147.0  0.0
 -71.0   -25.0  -126.0   94.0    55.0   -86.0  -147.0     0.0  0.0
   0.0     0.0     0.0    0.0     0.0     0.0     0.0     0.0  0.0

In [28]:
max_happiness(1, 2:length(names)+1, newunits)

601.0